package com.winthier.skills;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum Perk {
    // Base Smithing Improvements
    SMITH_IMPROVE_LEATHER(SkillType.SMITH, null),
    SMITH_IMPROVE_GOLD(SkillType.SMITH, Perk.SMITH_IMPROVE_LEATHER),
    SMITH_IMPROVE_MAIL(SkillType.SMITH, Perk.SMITH_IMPROVE_GOLD),
    SMITH_IMPROVE_IRON(SkillType.SMITH, Perk.SMITH_IMPROVE_MAIL),
    SMITH_IMPROVE_DIAMOND(SkillType.SMITH, Perk.SMITH_IMPROVE_IRON),
    // Smithing Armor Perks
    SMITH_LEATHER_ARMOR_SPEED(SkillType.SMITH, Perk.SMITH_IMPROVE_LEATHER),
    SMITH_GOLD_ARMOR_HEALTH(SkillType.SMITH, Perk.SMITH_IMPROVE_GOLD),
    SMITH_MAIL_ARMOR_DAMAGE(SkillType.SMITH, Perk.SMITH_IMPROVE_MAIL),
    SMITH_IRON_ARMOR_ARMOR(SkillType.SMITH, Perk.SMITH_IMPROVE_IRON),
    SMITH_IRON_ARMOR_DAMAGE(SkillType.SMITH, Perk.SMITH_IRON_ARMOR_ARMOR),
    SMITH_DIAMOND_ARMOR_ARMOR(SkillType.SMITH, Perk.SMITH_IMPROVE_DIAMOND),
    SMITH_DIAMOND_ARMOR_TOUGH(SkillType.SMITH, Perk.SMITH_DIAMOND_ARMOR_ARMOR),
    SMITH_DIAMOND_ARMOR_KNOCKBACK_RESIST(SkillType.SMITH, Perk.SMITH_DIAMOND_ARMOR_TOUGH),
    SMITH_SHIELD_ARMOR(SkillType.SMITH, Perk.SMITH_IMPROVE_IRON),
    SMITH_SWORD_DAMAGE(SkillType.SMITH, Perk.SMITH_IMPROVE_IRON),
    // Brawl Swords
    BRAWL_SWORD_DAMAGE(SkillType.BRAWL, null),
    BRAWL_SWORD_SMART_KNOCKBACK(SkillType.BRAWL, null),
    BRAWL_SWORD_KNOCKOUT(SkillType.BRAWL, null),
    BRAWL_SWORD_VAMIRISM(SkillType.BRAWL, null),
    BRAWL_SWORD_POISON(SkillType.BRAWL, null),
    BRAWL_SWORD_WITHER(SkillType.BRAWL, null),
    // Brawl Axes
    BRAWL_AXE_DAMAGE(SkillType.BRAWL, null),
    BRAWL_AXE_AOE(SkillType.BRAWL, null),
    BRAWL_AXE_KNOCKBACK(SkillType.BRAWL, null),
    BRAWL_AXE_SLOWNESS(SkillType.BRAWL, null),
    BRAWL_AXE_FIRE(SkillType.BRAWL, null),
    // Brawl Unarmed
    BRAWL_UNARMED_DAMAGE(SkillType.BRAWL, null),
    BRAWL_UNARMED_DISARM(SkillType.BRAWL, null),
    BRAWL_UNARMED_KNOCKOUT(SkillType.BRAWL, null),
    BRAWL_UNARMED_STEAL(SkillType.BRAWL, null),
    // Breeding Base
    BREED_MORE_BABIES(SkillType.BREED, null),
    BREED_IMPROVE_COW(SkillType.BREED, Perk.BREED_MORE_BABIES),
    BREED_IMPROVE_PIG(SkillType.BREED, Perk.BREED_IMPROVE_COW),
    BREED_IMPROVE_SHEEP(SkillType.BREED, Perk.BREED_IMPROVE_PIG),
    BREED_IMPROVE_CHICKEN(SkillType.BREED, Perk.BREED_IMPROVE_SHEEP),
    BREED_IMPROVE_RABBIT(SkillType.BREED, Perk.BREED_IMPROVE_CHICKEN),
    BREED_IMPROVE_HORSE(SkillType.BREED, Perk.BREED_MORE_BABIES),
    BREED_IMPROVE_DONKEY(SkillType.BREED, Perk.BREED_IMPROVE_HORSE),
    BREED_IMPROVE_DOG(SkillType.BREED, Perk.BREED_MORE_BABIES),
    BREED_IMPROVE_CAT(SkillType.BREED, Perk.BREED_IMPROVE_DOG),
    // Breeding Specific
    BREED_FINE_LEATHER(SkillType.BREED, Perk.BREED_IMPROVE_COW),
    BREED_CAT_TREASURE(SkillType.BREED, Perk.BREED_IMPROVE_CAT),
    BREED_PIG_TRUFFLE(SkillType.BREED, Perk.BREED_IMPROVE_PIG),
    BREED_SHEEP_RAINBOW(SkillType.BREED, Perk.BREED_IMPROVE_SHEEP),
    BREED_CHICKEN_GOLD(SkillType.BREED, Perk.BREED_IMPROVE_CHICKEN),
    BREED_HORSE_SKELETON(SkillType.BREED, Perk.BREED_IMPROVE_HORSE),
    BREED_HORSE_ZOMBIE(SkillType.BREED, Perk.BREED_HORSE_SKELETON),
    // Brewing
    BREW_STACK(SkillType.BREW, null),
    // Brewing for yourself
    BREW_MOVEMENT_DURATION(SkillType.BREW, Perk.BREW_STACK),
    BREW_RESISTANCE_DURATION(SkillType.BREW, Perk.BREW_MOVEMENT_DURATION),
    BREW_ABILITY_DURATION(SkillType.BREW, Perk.BREW_RESISTANCE_DURATION),
    BREW_RESISTANCE_ABSORPTION(SkillType.BREW, Perk.BREW_ABILITY_DURATION),
    BREW_HEAL_REGEN(SkillType.BREW, Perk.BREW_RESISTANCE_ABSORPTION),
    BREW_REGEN_HEALTH(SkillType.BREW, Perk.BREW_HEAL_REGEN),
    // Brewing to hurt enemies
    BREW_DEBUFF_DURATION(SkillType.BREW, Perk.BREW_STACK),
    BREW_DAMAGE_POISON(SkillType.BREW, Perk.BREW_DEBUFF_DURATION),
    BREW_WEAK_BLIND(SkillType.BREW, Perk.BREW_DAMAGE_POISON),
    BREW_SLOW_WITHER(SkillType.BREW, Perk.BREW_WEAK_BLIND),
    // Cook
    COOK_SATURATION(SkillType.COOK, null),
    COOK_MEAT_RESISTANCE(SkillType.COOK, null),
    COOK_VEGETABLE_HEALTH(SkillType.COOK, null),
    COOK_STARCH_STRENGTH(SkillType.COOK, null),
    COOK_SUGAR_SPEED(SkillType.COOK, null),
    COOK_FISH_ABSORPTION(SkillType.COOK, null),
    // Digging
    DIG_BONE(SkillType.DIG, null),
    DIG_STRING(SkillType.DIG, null),
    DIG_FEATHER(SkillType.DIG, null),
    DIG_GUNPOWDER(SkillType.DIG, null),
    DIG_SEEDS(SkillType.DIG, null),
    DIG_IRON(SkillType.DIG, null),
    DIG_GOLD(SkillType.DIG, null),
    DIG_EMERALD(SkillType.DIG, null),
    DIG_DIAMOND(SkillType.DIG, null),
    DIG_FALLING_STACK(SkillType.DIG, null),
    DIG_RADIUS(SkillType.DIG, null),
    // Enchanting
    ENCHANT_TOP_OPTIONS(SkillType.ENCHANT, null),
    ENCHANT_(SkillType.ENCHANT, null),
    // Fishing
    // 
    ;

    final SkillType skillType;
    final Perk depends;
}
