name: Skills
description: Skills system for Winthier
author: StarTux
version: 0.4
main: com.winthier.skills.SkillsPlugin
depend: [ SQL, Exploits, PlayerCache, Custom ]
commands: {}
permissions:
  skills.skill.*:
    description: Use all skills
    default: false
  skills.skills:
    description: Use the /skills command
    default: op
  skills.highscore:
    description: Use the /highscore command
    default: op
  skills.admin:
    description: Perform admin tasks
    default: op
commands:
  skills:
    aliases: [ skill, sk ]
    permission: skills.skills
  highscore:
    aliases: [ hi, hiscore, highscores, hiscores ]
    permission: skills.highscore
  skillsadmin:
    aliases: [ skilladmin, skadmin ]
    permission: skills.admin
